services:
  - type: web
    name: battleship-game
    env: node
    buildCommand: npm install
    startCommand: npm run prod
    envVars:
      - key: MONGO
        value: "mongodb+srv://liacenyjdafa:CyjzmI0812@cluster0.zzspr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: NODE_VERSION
        value: "16.x"
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/users/scores
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
