services:
  - type: web
    name: battleship-game
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO
        value: "mongodb+srv://liacenyjdafa:CyjzmI0812@cluster0.zzspr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: NODE_VERSION
        value: "16.x"
      - key: JWT_SECRET
        generateValue: true
      - key: CI
        value: "true"
    healthCheckPath: /api/users/scores
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
